apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btree-claim
  namespace: p4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpointversion-claim
  namespace: p4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 5Gi
  storageClassName: standard
---

#apiVersion: v1
#kind: Service
#metadata:
#  name: p4d-svc
#  labels:
#    app: p4d
#  namespace: p4
#spec:
#  type: LoadBalancer
#  ports:
#  - port: 4232
#    name: p4d-port
#    targetPort: 4232
#  selector:
#    app: p4d
#    server: master
#  externalTrafficPolicy: Local

apiVersion: v1
kind: Service
metadata:
  name: p4d-svc
  labels:
    app: p4d
  namespace: p4
spec:
  type: ClusterIP
  ports:
  - port: 4232
    name: p4d-port
    targetPort: 4232
  selector:
    app: p4d
    server: master
  
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: p4d-state
  namespace: p4
spec:
  selector:
    matchLabels:
      app: p4d # has to match .spec.template.metadata.labels
      server: master
  serviceName: "p4d-svc"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0,
  template:
    metadata:
      labels:
        app: p4d # has to match .spec.selector.matchLabels
        server: master
    spec:
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
        fsGroup: 1337
      containers:
      - name: p4d-ctr
        image: immnan/p4d:0.2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 4232
          name: p4d-port
        volumeMounts:
        - name: btree
          mountPath: /var/p4d-root/
        - name: checkpoint
          mountPath: /var/p4d-checkpoint/
        - name: version-files
          mountPath: /var/p4d-versionfiles/
      volumes:
      - name: btree
        persistentVolumeClaim:
          claimName: btree-claim
      - name: checkpoint
        persistentVolumeClaim:
          claimName: checkpointversion-claim
      - name: version-files
        persistentVolumeClaim:
          claimName: checkpointversion-claim
