apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btree-claim
  namespace: p4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 10Gi
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkpointversion-claim
  namespace: p4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 5Gi
  storageClassName: standard
---