p4dSpec: 
- server: 
    sts: p4d # from the yaml manifest
    type: master
    name: p4d-state-0 # From the ENV
    port: 4232
    services: commit-server
    address: p4d-state-0:4232
    Description: "P4D Master server"
    initConfig: 
      init: true
      p4dRootPath: /p4data
      ctrMounts: 
      - mountPath: /opt/p4d-root
        pvc: btree-claim
        pv: pvc-c23bf37b-d54a-4660-a282-8f5f6b2e6e2c
      - mountPath: /opt/p4d-check
        pvc: checkpointversion-claim
        pv: pvc-25cba357-43f9-42b3-b171-e776e22a16ab
      distributedConfig: /path/to/config/file  
