apiVersion: v1
kind: ConfigMap
metadata:
  name: p4C-config
  namespace: p4
  labels:
    app: p4d 
    managed-by: p4controller
data:
  p4Controller_config.yaml: |
    p4CSpec:
      p4d-state-0:
        stsName: p4d-state
        podType: master
        podPort: 4232
        services: commit-server
        type: server
        address: p4d-state-0:4232
        description: "P4D Master server"
        initConfig:
          init: true
          p4dRootPath: /p4data
          ctrMounts:
            - mountPath: /opt/p4d-root
              pvc: btree-claim
              pv: pvc-c23bf37b-d54a-4660-a282-8f5f6b2e6e2c
            - mountPath: /opt/p4d-check
              pvc: checkpointversion-claim
              pv: pvc-25cba357-43f9-42b3-b171-e776e22a16ab
        distributedConfig: /path/to/config/file
    
      p4d-replica-0:
        type: replica
        port: 4232
        services: replica-server
        address: p4d-replica-0:4232
        description: "P4D Replica server"
        initConfig:
          init: true
          p4dRootPath: /p4data
          ctrMounts:
            - mountPath: /opt/p4d-root
              pvc: btree-claim
              pv: pvc-c23bf37b-d54a-4660-8f5f6b2e6e2c
            - mountPath: /opt/p4d-check
              pvc: checkpointversion-claim
              pv: pvc-25cba357-43f9-b171-e776e22a16ab
        distributedConfig: /path/to/config/file