apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: p4controller-role
  namespace: p4
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: p4controller-rolebinding
  namespace: p4
subjects:
- kind: ServiceAccount
  name: default
  namespace: p4
roleRef:
  kind: Role
  name: p4controller-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: p4controller
  namespace: p4
spec:
  selector:
    matchLabels:
      app: p4controller 
  replicas: 1         
  template:
    metadata:
      labels:
        app: p4controller 
    spec:
      serviceAccountName: default
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 1337
        runAsGroup: 1337
        fsGroup: 1337
      containers:
      - name: p4controller-ctr
        image: immnan/p4c:0.1.1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: P4PORT
          value: "34.118.233.63:4232"
        - name: WORKING_NAMESPACE
          value: "p4"